Lab#1 variant#3
0x100/java-lessons pull request #13
Opened 2017-03-05 13:24 UTC by LysykhVladimir

Lysykh V/ Lab1 variant3

2017-03-12 19:39 UTC, 0x100 requested changes

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask1/model/SuperArray.java
> +            array[i] = rnd.nextInt(bound*2)-bound;
Зачем такая сложная формула? Одного nextInt по идее вполне достататочно :)

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask1/Main.java
> +        ConsoleView view = new ConsoleView(new SuperArray(20,100));
Условие задачи довольно простое, а с ООП тут код получился трудночитаемым. Достаточно показать саму реализацию алгоритма, попробуй упростить.

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask3/model/BadArray.java
> +        for (int i=0; i<numbers.length-1; i++){
Этот цикл лучше перенести в метод bubbleSort, а то с ходу не совсем ясно его предназначение

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask3/model/BadArray.java
> +            flag = flag + bubbleSort();
Попробуй тут оператор +=

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask3/model/BadArray.java
> +        int flag = 0;
Лучше назови переменную как-то со словом count.

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask1/Main.java
> +        ConsoleView view = new ConsoleView(new SuperArray(20,100));
Следующая лабораторная уже вероятно будет предполагать использование ООП

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Main.java
> +        Lock lock1 = new Lock();
За решение этой задачи плюс в карму :)

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Lock.java
> +            return true;
Так писать не надо, упрости метод до одного return, без использования if

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Cube.java
> +     boolean goodCube(int edge) {
Геттеры с булевым значением лучше называть со слова is, т.е. isGoodCube.

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Cube.java
> +            return true;
Упрости до одного return, без if

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Lock.java
> +    private Cube[] cube;
Массивы, списки, множества называй во множественном числе.

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Lock.java
> +    private boolean isOpen(int i,int j,int k){
Переменные называй по смыслу, названий типа i, j, k следует избегать, если к примеру это не переменная цикла.

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Lock.java
> +        return (this.cube[START_POSITION].EDGE_COUNT)+1;
Для получения константы EDGE_COUNT достаточно обратиться к классу Cube, т.е. Cube.EDGE_COUNT, объект в данном случае не нужен.

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Lock.java
> +        return (this.cube[START_POSITION].EDGE_COUNT)+1;
Зачем тут прибавляешь единицу, а в rndEdge ее отнимаешь?

2017-03-12 19:39 UTC, 0x100 commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Cube.java
> +    private boolean usage;
Не до конца понял смысл этого поля.

2017-03-13 21:18 UTC, LysykhVladimir commented on src/main/java/ru/tn/courses/vlysykh/task1/v3/subtask2/Cube.java
> +    private boolean usage;
поменял на isUsage. поле показывает, что кубик уже задействован в валидной комбинации и менять его не нужно до поиска следующей валидной комбинации,

2017-05-25 19:04 UTC, closed without merging