Задача на подстроки
0x100/java-lessons pull request #26
Opened 2017-03-12 18:41 UTC by mgrebnev

2017-03-12 20:41 UTC, 0x100 requested changes

2017-03-12 20:41 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +/**
Где пакет?

2017-03-12 20:41 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        ArrayList substring = new ArrayList();
Используй интерфейс, а не конкретную реализацию для указания типа переменной, там где возможно. В данном случае List или Collection. В ближайших лекциях о них расскажем.

2017-03-12 20:41 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        int len_wrd = 2;
Название переменной не соответствует конвенции именования http://www.oracle.com/technetwork/java/codeconventions-135099.html.

2017-03-12 20:41 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +                for ( int k = 0; k < len_wrd; k++){
Чтобы избавиться от 3-го вложенного цикла попробуй воспользоваться методом substring класса строки.

2017-03-12 20:41 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        System.out.println("\n" + "word = " + result + " count = " + temp);
В твоем решении учитывается только частота вхождения подстроки, а длина - нет.

2017-03-12 20:41 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        int temp = 0;
Почему temp? Дай более осмысленное название, к примеру говорящее что это максимальное количество или частота...

2017-03-13 07:10 UTC, mgrebnev commented
Изменил

2017-03-21 21:14 UTC, 0x100 requested changes
Твоя программа вывела:

Кол-во подстрок =  153
Подстрока  до  встречается 2 раз
Подстрока  ом  встречается 2 раз
Подстрока  мк  встречается 2 раз
Подстрока  ку  встречается 4 раз
Подстрока  уб  встречается 4 раз
Подстрока  куб  встречается 4 раз

Подстроки с длинной 2:
 
до  встречаются 2 раз 
ом  встречаются 2 раз 
мк  встречаются 2 раз 
ку  встречаются 4 раз 
уб  встречаются 4 раз 

По условию требовалось вывести так: куб, 4

2017-03-21 21:14 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        ArrayList subStrings = new ArrayList();
Нетипизированный список, укажи тип. Также исправь тип переменной на интерфейс, вместо конкретной реализации (ArrayList).

2017-03-21 21:14 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        ArrayList subWord = new ArrayList();
То же, что в комментарии выше

2017-03-22 14:55 UTC, mgrebnev commented
Должно работать правильно)

2017-03-22 15:07 UTC, 0x100 requested changes
Да, сейчас работает правильно. Исправь пару мелких замечаний, будет принято.

2017-03-22 15:07 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        List<String> subWord = new ArrayList();
У ArrayList тоже нужно либо тип указать, либо даймонд <>.

2017-03-22 15:07 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +        List<String> subWord = new ArrayList();
У ArrayList тоже нужно либо тип указать, либо даймонд <>.

2017-03-22 15:07 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +                if(!subWord.contains(subStrings.get(i).toString())){
вызов метода toString() в данном случае лишний

2017-03-23 08:26 UTC, 0x100 approved these changes
один toString() оставил лишний

2017-03-23 08:26 UTC, 0x100 commented on src/main/java/ru/tn/courses/mgrebnev/task1/v4/subtask4/Main.java
> +                    subWord.add(subStrings.get(i).toString());
Лишний toString()

2017-03-23 08:26 UTC, merged