Лабораторная работа
0x100/java-lessons pull request #4
Opened 2017-03-02 20:36 UTC by baneblade22

2017-03-02 21:16 UTC, 0x100 commented
После выполнения задания выполнить pull request, **_ревьюерами кода выбрать_**:
**_rnemykin
0x100_**

2017-03-02 21:17 UTC, 0x100 commented
Где ревьюеры?

2017-03-02 21:33 UTC, baneblade22 commented
не могу добавить и не знаю, что с этим делать

2017-03-06 22:06 UTC, baneblade22 commented
Вот еще задача вторая с третьего варианта
только я там забыл свич упростить немного

2017-03-09 20:22 UTC, rnemykin commented
сделай структуру пакетов, как описано в READ.ME

2017-03-11 09:48 UTC, 0x100 requested changes

2017-03-11 09:48 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask1v4/Main.java
> +package ru.tn.courses.task1subtask1v4;
Пакет сформирован не так как оговорено:

> Cоздаем пакет с номером варианта **ru.tn.courses.mmaters.task1.v5**.
> Под каждое задание создаем пакет subtask_номер-задания-в-л-р
> 
> **ru.tn.courses.mmaters.task1.v5.subtask1**
> ru.tn.courses.mmaters.task1.v5.subtask2
> ru.tn.courses.mmaters.task1.v5.subtask3

2017-03-11 09:48 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask1v4/Main.java
> +        int n = 37;
Название переменной лучше давать осмысленное (касательно bool, k, n).

2017-03-11 09:48 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask1v4/Main.java
> +        int[] mas = new int[k];
Не приучайся называть переменные транслитом, лучше использовать название на англ.языке.

2017-03-11 09:48 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask1v4/Main.java
> +                break;
В качестве доп.задания, выполни рефакторинг, вынеся логику проверки последовательности на возрастание в отдельный метод, избавившись при этом от использования булевой переменной и break.

2017-03-11 09:48 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v4/Main.java
> +}
Те же замечания, что в предыдущем задании.

2017-03-11 09:48 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask3v4/Main.java
> +            mas[i] = (int) (Math.random() * k);
Попробуй использовать тут класс java.util.Random, чтобы избавиться от приведения к int и умножения на коэффициент.

2017-03-11 09:48 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v3/Main.java
> +    public static int it1 = 22; // место кубика в массиве
Откуда 22, если по условию 10 ячеек?

2017-03-12 16:47 UTC, baneblade22 commented
всё, успех
только первое лишнее, случайно добавил

2017-03-21 21:34 UTC, 0x100 requested changes
Миша, все фигня, давай по новой!

Второе задание работает неверно:
1 элемент = 8
2 элемент = 10
4 элемент = 7
8 элемент = 12
16 элемент = 12
32 элемент = 12
Массив:
[6, 8, 10, 9, 7, 9, 3, 14, 12, 11, 18, 19, 15, 0, 11, 5, 12, 8, 17, 0, 15, 3, 9, 17, 12, 9, 1, 11, 18, 17, 9, 3, 12]

2017-03-23 14:47 UTC, 0x100 requested changes
Во втором все-таки все нормально, но вывести требовалось только элементы. Исправь замечания по задаче с сейфом.

2017-03-23 14:47 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v3/Main.java
> +                switch (group2) {
По сути дубль кода выше, вынеси в метод.

2017-03-23 14:47 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v3/Main.java
> +    public static int[] rand(int[] mas) {
Неиспользуемый метод, удали.

2017-03-23 14:47 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v3/Main.java
> +        int [] indeces = new int[2];
indices

2017-03-23 14:47 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v3/Main.java
> +        LinkedList<Integer> used = new LinkedList<>();
Укажи в качестве типа переменной списка интерфейс вместо конкретной реализации.

2017-03-23 14:47 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v3/Main.java
> +package ru.tn.courses.task1subtask2v3;
Неверная структура пакета

2017-03-23 14:47 UTC, 0x100 commented on src/main/java/ru/tn/courses/task1subtask2v3/Main.java
> +    public static int[] masNumber = new int[10];
Данные поля можно сделать приватными

2017-03-23 14:53 UTC, rnemykin approved these changes

2017-03-23 14:53 UTC, merged